### PR TITLE
Feat/segment io renaming

### PR DESCRIPTION
**Pull request by Mancini-Rafael**
- PR objective: Refactor the gem to allow use of SegmentIO namespace to prevent conflicts

- Changes:
  - Replaces all segment mentions to Segment::IO through the use of the build.sh script
- How to install: bundle install
- How to test locally: bundle exec rspec spec
- How to test using rails application
  - add the following line to gemfile: 
  - `gem 'analytics-ruby', '~> 2.4.0', require: false, git: 'https://github.com/Junglescout/analytics-ruby.git', branch: 'feat/segment-io-renaming'`

### CODE REVIEW

**Review by ArmandoKenneth — APPROVED** [review]
LGTM, let's wait for one more approval. Can you ask in the developers channel asking for reviews today?

**Comment by rauldudu** [comment]
Do you think the file names and folders could keep the same? Or that would break something?

Wouldn't that make easier to cherry pick changes?

**Comment by Mancini-Rafael** [comment]
> Do you think the file names and folders could keep the same? Or that would break something?
> 
> Wouldn't that make easier to cherry pick changes?

I'm pretty sure it wouldn't work because of Zeitwerk (files ```something.rb``` expecting constants ```Something``` to be defined). Also, I'm not sure if this is a good idea because it makes for unexpected constants being in unexpected places. And the goal of the PR is to totally get rid of the Segment namespace, in all accounts

**Comment by rauldudu** [comment]
> > Do you think the file names and folders could keep the same? Or that would break something?
> > Wouldn't that make easier to cherry pick changes?
> 
> I'm pretty sure it wouldn't work because of Zeitwerk (files `something.rb` expecting constants `Something` to be defined). Also, I'm not sure if this is a good idea because it makes for unexpected constants being in unexpected places. And the goal of the PR is to totally get rid of the Segment namespace, in all accounts

Good point 👍

**Pull request merged**
